### PR TITLE
OwmClient's objects will be immutable since this change

### PR DESCRIPTION
**Pull request by Cs4r**
- Now OwmClient's objects are immutable so that we might use same instance in multiple threads
- Modified tests according to new changes

### CODE REVIEW

**Comment by migtavares** [comment]
I need some time to review the pull request.
Seems like a lot of changes are cosmetic - I do like to keep line count lowers by having compact comment blocks, like to have the function and the opening parenthesis without any space in between and other idiosyncrasies like that from an old timer used to 80x25 chars in the terminal.

On a quick view it looks like the relevant change is making the APPID local to each OwmClient. Correct?

**Comment by Cs4r** [comment]
I see what you mean, I am using Eclipse's format functionality (Shift+Ctrl+F) which provides that sort of java formatting. I do like it since it's very widespread.

Regarding to the real changes, I just removed the availability of setting the apiKey for a OwmClient object once constructed (setAPPID method removed). Besides I added a new test (testPublicConstructorWithNullApiKey) to ensure is not possible instantiate a OwmClient with a null apiKey.

No problem for waiting for the pull request confirmation, however take into account that more minor improvements are coming from my side :smile:

**Comment by migtavares** [comment]
Doesn't this break API compatibility?
I would be more comfortable with deprecating the current API and making this the preferred interface. Is that OK for your purposes?
Regarding the code formatting - I have a Code Style formatter and I could share it.

**Comment by Cs4r** [comment]
Yes, you are right. It's a good a idea to create an interface and then have several implementations, for instance for 2.1 API one and for 2.5 API (current) another one.

I would recommend you to cancel this pull request because I  am making a new one in a few days/weeks with the interface you have proposed which also will include a new method like the next:

```
forecastWeatherAtCity(String cityName, String countryCode) 
```

(previously it did not have the countryCode parameter)

PS: please, share the code style formatter with me whether following it is a requisite for merging changes.

**Comment by migtavares** [comment]
Regarding having the same interface for both API 2.1 and 2.5: I think it might be better to keep them in separate versions of ownClient. Version 2.1.n would be the implementation for API 2.1, version 2.5.n would be the implementation for API 2.5 (n being a number of bug fixes). I started doing this some time ago (I have a local 2.5 branch with some changes already but it's far from completion).

**Pull request closed without merging**
